const data={
    products:[{
        name:'product1',
        slug:'1',
        category:'electronic',
        image:'/images/image2.jpg',
        price:120,
        countInStock: 10,
        rating:4.5,
        description:'good',
    },
    {
        name:'product2',
        slug:'2',
        category:'electronic',
        image:'/images/image4.jpg',
        price:120,
        countInStock: 10,
        rating:4,
        description:'good',
    },
    {
        name:'product3',
        slug:'3',
        category:'electronic',
        image:'/images/image5.jpg',
        price:120,
        countInStock: 10,
        rating:5,
        description:'very good',
    },
    {
        name:'product5',
        slug:'5',
        category:'electronic',
        image:'/images/image5.jpg',
        price:120,
        countInStock: 10,
        rating:4.5,
        description:'good',
    },
    {
        name:'product6',
        slug:'6',
        category:'electronic',
        image:'/images/image2.jpg',
        price:120,
        countInStock: 10,
        rating:4.5,
        description:'good',
    },
    {
        name:'product7',
        slug:'7',
        category:'electronic',
        image:'/images/meuble.jpg',
        price:120,
        countInStock: 10,
        rating:4.5,
        description:'good',
    },],
}
export default data;